#!/usr/bin/env python3
"""
Generates the .lproj localization files from the hand-edited JSON sources, and
verifies that every string the app asks for at runtime actually exists.

Why a script
------------
This project is built entirely in CI: there is no Mac to open Xcode on, so the
usual workflow (Xcode extracts strings into a String Catalog and shows you a
"needs translation" badge) is not available. Nothing would notice a missing
Hebrew string until it appeared, in English, in the middle of a Hebrew screen.

So the check happens here instead. Run with --check in CI: it re-scans the Swift
sources for localizable strings and fails if any of them has no Hebrew
translation, or if any translation exists for a string the code no longer uses.
That second direction matters as much as the first — stale entries are how a
localization file slowly becomes fiction.

Usage:
    python3 Scripts/build_localizations.py           # write the .lproj files
    python3 Scripts/build_localizations.py --check   # verify only, exit 1 on drift
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "Scripts"

# Diagnostics is deliberately NOT localized: it is a developer instrument whose
# whole purpose is to be exported as text and read by whoever is debugging.
# Translating it would make shared reports harder to compare, not easier to read.
EXCLUDED_FILES = {"DiagnosticsScreen.swift"}

# Pure-number formats. A "translation" of these could only ever be an identity
# mapping, so requiring one would be busywork that later rots into a lie.
EXCLUDED_KEYS = {"%lld", "%lld%"}

SF_SYMBOL = re.compile(r"^[a-z0-9]+(\.[a-z0-9A-Z]+)+$")

# Call sites where a string literal becomes user-visible text. `sectionHeader`
# is this app's own helper; it is listed because it takes a `LocalizedStringKey`,
# so literals passed to it are localized exactly like a `Text`. Any future helper
# with a `LocalizedStringKey` parameter has to be added here too — otherwise its
# strings are translated in the app but invisible to this check, which is the
# quiet failure mode this script exists to prevent.
LOCALIZABLE_CONTEXT = re.compile(
    r"(?:Text|Label|Button|Section|Picker|Toggle|navigationTitle|confirmationDialog|alert|"
    r"accessibilityLabel|accessibilityHint|ContentUnavailableView|sectionHeader|"
    r"String\(localized:\s*)"
    r'\(?\s*"((?:[^"\\]|\\.)*)"'
)

# Interpolated expressions that produce a String (%@) rather than an Int (%lld).
STRING_VALUED = ("counted(", ".formatted(", "localizedDescription")
STRING_VALUED_EXACT = {"title", "category.title", "noun.singularName"}


def format_specifier(expression: str) -> str:
    expression = expression.strip()
    if any(hint in expression for hint in STRING_VALUED) or expression in STRING_VALUED_EXACT:
        return "%@"
    return "%lld"


def runtime_key(literal: str) -> str:
    """Turns a Swift literal with \\(interpolation) into the format string the
    localization system will actually look up."""
    out, i = [], 0
    while i < len(literal):
        if literal[i] == "\\" and i + 1 < len(literal) and literal[i + 1] == "(":
            depth, j = 1, i + 2
            while j < len(literal) and depth:
                if literal[j] == "(":
                    depth += 1
                elif literal[j] == ")":
                    depth -= 1
                j += 1
            out.append(format_specifier(literal[i + 2:j - 1]))
            i = j
        else:
            out.append(literal[i])
            i += 1
    return "".join(out)


def scan_source_keys() -> set:
    keys = set()
    for folder in ("Views", "Models"):
        for path in sorted((ROOT / folder).glob("*.swift")):
            if path.name in EXCLUDED_FILES:
                continue
            source = re.sub(r"^\s*//.*$", "", path.read_text(encoding="utf-8"), flags=re.M)
            for match in LOCALIZABLE_CONTEXT.finditer(source):
                literal = match.group(1)
                if len(literal) < 2 or SF_SYMBOL.match(literal):
                    continue
                keys.add(runtime_key(literal))
    return keys - EXCLUDED_KEYS


def noun_cases() -> list:
    """The ItemNoun cases, read from the Swift source so this file cannot drift
    out of step with the enum."""
    source = (ROOT / "Models" / "ItemNoun.swift").read_text(encoding="utf-8")
    body = source.split("enum ItemNoun", 1)[1]
    return re.findall(r"^\s*case (\w+)$", body, flags=re.M)


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_strings(path: pathlib.Path, mapping: dict, note: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"/* {note} */", "/* Generated by Scripts/build_localizations.py — do not edit by hand. */", ""]
    for key in sorted(mapping):
        lines.append(f'"{escape(key)}" = "{escape(mapping[key])}";')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_stringsdict(path: pathlib.Path, plurals: dict, language: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        '<plist version="1.0">',
        "<dict>",
    ]
    for key in sorted(k for k in plurals if not k.startswith("_")):
        forms = plurals[key][language]
        out += [
            f"\t<key>{key}</key>",
            "\t<dict>",
            "\t\t<key>NSStringLocalizedFormatKey</key>",
            "\t\t<string>%#@items@</string>",
            "\t\t<key>items</key>",
            "\t\t<dict>",
            "\t\t\t<key>NSStringFormatSpecTypeKey</key>",
            "\t\t\t<string>NSStringPluralRuleType</string>",
            "\t\t\t<key>NSStringFormatValueTypeKey</key>",
            "\t\t\t<string>lld</string>",
        ]
        # "other" is the only category the system guarantees to fall back on, so
        # it must always be present. The rest are language dependent.
        for category in ("zero", "one", "two", "few", "many", "other"):
            if category in forms:
                out += [f"\t\t\t<key>{category}</key>", f"\t\t\t<string>{forms[category]}</string>"]
        out += ["\t\t</dict>", "\t</dict>"]
    out += ["</dict>", "</plist>", ""]
    path.write_text("\n".join(out), encoding="utf-8")


def main() -> int:
    check_only = "--check" in sys.argv

    hebrew = {k: v for k, v in json.loads((SCRIPTS / "hebrew.json").read_text(encoding="utf-8")).items()
              if not k.startswith("_")}
    plurals = {k: v for k, v in json.loads((SCRIPTS / "plurals.json").read_text(encoding="utf-8")).items()
               if not k.startswith("_")}

    source_keys = scan_source_keys()
    nouns = noun_cases()
    singular_keys = {f"noun.{case}.singular" for case in nouns}
    expected = source_keys | singular_keys

    problems = []

    missing = sorted(expected - set(hebrew))
    if missing:
        problems.append(f"No Hebrew translation for {len(missing)} string(s):")
        # No `%`-formatting here: the keys themselves contain %@ and %lld, which
        # a format operation would try to consume as placeholders and crash on.
        problems += [f"    {key!r}" for key in missing]

    stale = sorted(set(hebrew) - expected)
    if stale:
        problems.append(f"Hebrew translations for {len(stale)} string(s) the code no longer uses:")
        problems += [f"    {key!r}" for key in stale]

    missing_plurals = sorted({f"count.{case}" for case in nouns} - set(plurals))
    if missing_plurals:
        problems.append("ItemNoun cases with no plural forms: " + ", ".join(missing_plurals))

    for key, forms in plurals.items():
        for language in ("en", "he"):
            if language not in forms:
                problems.append(f"{key}: no {language} plural forms")
            elif "other" not in forms[language]:
                problems.append(f"{key} [{language}]: missing the required 'other' category")

    # A format specifier that appears in the key must appear in the translation,
    # or the argument silently vanishes at runtime.
    for key, value in hebrew.items():
        for specifier in ("%@", "%lld"):
            if specifier in key and specifier not in value and "%1$" not in value and "%2$" not in value:
                problems.append(f"{key!r}: Hebrew drops the {specifier} argument")

    if problems:
        print("Localization check FAILED\n")
        print("\n".join(problems))
        return 1

    print(f"Localization OK — {len(expected)} strings, {len(plurals)} pluralized nouns.")

    if check_only:
        return 0

    english = {key: key for key in source_keys}
    english.update({f"noun.{case}.singular": case_to_english(case) for case in nouns})

    write_strings(ROOT / "Resources" / "en.lproj" / "Localizable.strings", english,
                  "English (source language).")
    write_strings(ROOT / "Resources" / "he.lproj" / "Localizable.strings", hebrew,
                  "Hebrew. Edit Scripts/hebrew.json, not this file.")
    write_stringsdict(ROOT / "Resources" / "en.lproj" / "Localizable.stringsdict", plurals, "en")
    write_stringsdict(ROOT / "Resources" / "he.lproj" / "Localizable.stringsdict", plurals, "he")
    print("Wrote Resources/en.lproj and Resources/he.lproj")
    return 0


def case_to_english(case: str) -> str:
    """foodPhoto -> Food photo."""
    spaced = re.sub(r"(?<!^)([A-Z])", lambda m: " " + m.group(1).lower(), case)
    return spaced[0].upper() + spaced[1:]


if __name__ == "__main__":
    sys.exit(main())
